feat: output metadata
MapIV/pointcloud_divider pull request #1
Opened 2023-03-23 12:19 UTC by kminoda

2023-03-28 02:13 UTC, kminoda commented
@Tomoya-Sato map4_point_typesの件も含めて対応終了したのでレビューをお願いいたします :pray:

2023-03-29 08:34 UTC, Tomoya-Sato requested changes
@kminoda PRありがとうございます。いくつかコメントを残しましたので修正をお願いします。

2023-03-29 08:34 UTC, Tomoya-Sato commented on CMakeLists.txt
> +ament_package()
ファイル末尾は改行の追加をお願いします

2023-03-29 08:34 UTC, Tomoya-Sato commented on README.md
> +D.pcd: [1400, 2650] # -> 1400 < x < 1500, 2650 < y < 2800
グリッドの定義上は下限は含むので
```
1200 <= x < 1300, 2500 <= y < 2650
```
の方がより正確だと思います

2023-03-29 08:34 UTC, Tomoya-Sato commented on package.xml
> +</package>
ファイル末尾は改行の追加をお願いします

2023-03-29 09:44 UTC, kminoda commented on CMakeLists.txt
> +ament_package()
対応完了しました　https://github.com/MapIV/pointcloud_divider/pull/1/commits/a46756f91670661dde5f68a35b92660a9e8c2cc9

2023-03-29 09:44 UTC, kminoda commented on README.md
> +D.pcd: [1400, 2650] # -> 1400 < x < 1500, 2650 < y < 2800
対応完了しました　https://github.com/MapIV/pointcloud_divider/pull/1/commits/a46756f91670661dde5f68a35b92660a9e8c2cc9

2023-03-29 09:44 UTC, kminoda commented on package.xml
> +</package>
対応完了しました　https://github.com/MapIV/pointcloud_divider/pull/1/commits/a46756f91670661dde5f68a35b92660a9e8c2cc9

2023-03-29 09:50 UTC, Tomoya-Sato approved these changes
LGTM

2023-03-29 09:50 UTC, merged